# Generated by Django 4.1.5 on 2023-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datanasabah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Databukutabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noidentitas', models.IntegerField()),
                ('norekening', models.IntegerField()),
                ('cabang', models.CharField(max_length=50, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('saldonominal', models.IntegerField()),
                ('saldoemas', models.IntegerField()),
                ('nama', models.ManyToManyField(to='datanasabah.datanasabah')),
            ],
        ),
    ]
