# Generated by Django 4.1.5 on 2023-01-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databukutabungan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databukutabungan',
            name='noidentitas',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='databukutabungan',
            name='norekening',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
