# Generated by Django 4.1.5 on 2023-01-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databukutabungan', '0002_alter_databukutabungan_noidentitas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databukutabungan',
            name='saldoemas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='databukutabungan',
            name='saldonominal',
            field=models.IntegerField(null=True),
        ),
    ]
