# Generated by Django 4.1.5 on 2023-01-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databukutabungan', '0003_alter_databukutabungan_saldoemas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databukutabungan',
            name='nama',
        ),
    ]
