# Generated by Django 4.1.5 on 2023-01-18 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datanasabah', '0002_alter_datanasabah_nama'),
        ('databukutabungan', '0004_remove_databukutabungan_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='databukutabungan',
            name='nama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datanasabah.datanasabah'),
        ),
    ]
