# Generated by Django 4.1.5 on 2023-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datanasabah', '0001_initial'),
        ('datasampah', '0001_initial'),
        ('databukutabungan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapembeliansampah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('berat', models.IntegerField()),
                ('jumlah', models.IntegerField()),
                ('jenissampah', models.ManyToManyField(to='datasampah.datasampah')),
                ('nama', models.ManyToManyField(to='datanasabah.datanasabah')),
                ('norekening', models.ManyToManyField(to='databukutabungan.databukutabungan')),
            ],
        ),
    ]
