# Generated by Django 4.1.5 on 2023-01-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapembeliansampah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapembeliansampah',
            name='kdpembeliansampah',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
