# Generated by Django 4.1.5 on 2023-01-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapembeliansampah', '0002_datapembeliansampah_kdpembeliansampah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapembeliansampah',
            name='kdpembeliansampah',
        ),
    ]
