# Generated by Django 4.1.5 on 2023-01-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapembeliansampah', '0004_remove_datapembeliansampah_nama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapembeliansampah',
            name='kdpembeliansampah',
        ),
    ]
