# Generated by Django 4.1.5 on 2023-01-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databukutabungan', '0005_databukutabungan_nama'),
        ('datapembeliansampah', '0007_remove_datapembeliansampah_jenissampah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapembeliansampah',
            name='norekening',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databukutabungan.databukutabungan'),
        ),
    ]
