# Generated by Django 4.1.5 on 2023-01-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapembeliansampah', '0008_alter_datapembeliansampah_norekening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapembeliansampah',
            name='jumlah',
            field=models.IntegerField(null=True),
        ),
    ]
