# Generated by Django 4.1.5 on 2023-01-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databukutabungan', '0001_initial'),
        ('datanasabah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapenarikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('keterangan', models.CharField(max_length=100, null=True)),
                ('waktudibuat', models.DateTimeField(auto_now_add=True, null=True)),
                ('bukutabungan', models.ManyToManyField(to='databukutabungan.databukutabungan')),
                ('nama', models.ManyToManyField(to='datanasabah.datanasabah')),
            ],
        ),
    ]
