# Generated by Django 4.1.5 on 2023-01-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databukutabungan', '0005_databukutabungan_nama'),
        ('datapenarikan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapenarikan',
            name='bukutabungan',
        ),
        migrations.AddField(
            model_name='datapenarikan',
            name='bukutabungan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databukutabungan.databukutabungan'),
        ),
    ]
