# Generated by Django 4.1.5 on 2023-01-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapenarikan', '0002_remove_datapenarikan_bukutabungan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapenarikan',
            name='nama',
        ),
    ]
