# Generated by Django 4.1.5 on 2023-01-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapenarikan', '0003_remove_datapenarikan_nama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapenarikan',
            old_name='bukutabungan',
            new_name='norekening',
        ),
    ]
