# Generated by Django 4.1.5 on 2023-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasampah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenissampah', models.CharField(choices=[('GB', 'Gelas Bening'), ('GW', 'Gelas Warna'), ('BB', 'Botol Bening'), ('BW', 'Botol Warna'), ('P', 'Plastik'), ('B', 'Besi'), ('K', 'Kardus')], max_length=15)),
                ('hargajual', models.IntegerField()),
                ('hargabeli', models.IntegerField()),
                ('margin', models.IntegerField()),
                ('waktudibuat', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
