# Generated by Django 4.1.5 on 2023-01-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasampah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasampah',
            name='jenissampah',
            field=models.CharField(choices=[('Gelas Bening', 'Gelas Bening'), ('Gelas Warna', 'Gelas Warna'), ('Botol Bekas', 'Botol Bening'), ('Botol Warna', 'Botol Warna'), ('Plastik', 'Plastik'), ('Besi', 'Besi'), ('Kardus', 'Kardus')], max_length=15),
        ),
    ]
