# Generated by Django 4.1.5 on 2023-01-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasampah', '0002_alter_datasampah_jenissampah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasampah',
            name='margin',
            field=models.IntegerField(null=True),
        ),
    ]
