# Generated by Django 4.1.5 on 2023-01-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datanasabah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100, null=True)),
                ('nohp', models.CharField(max_length=15, null=True)),
                ('jumlahanggota', models.CharField(max_length=3, null=True)),
                ('waktudibuat', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
