# Generated by Django 4.1.5 on 2023-01-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datanasabah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanasabah',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
